# Generated by Django 3.2.15 on 2022-09-24 16:30

import colander.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of this file.', primary_key=True, serialize=False)),
                ('extension', models.CharField(blank=True, max_length=64, null=True)),
                ('original_name', models.CharField(blank=True, max_length=512, null=True)),
                ('stored_name', models.CharField(blank=True, max_length=512, null=True)),
                ('storage_name', models.CharField(blank=True, max_length=64, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=512, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=512, null=True)),
                ('detached_signature', models.TextField(blank=True, null=True)),
                ('md5', models.CharField(blank=True, max_length=65, null=True)),
                ('sha1', models.CharField(blank=True, max_length=65, null=True)),
                ('sha256', models.CharField(blank=True, max_length=65, null=True)),
                ('size_in_bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date of your experiment.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Latest modification of your experiment.')),
                ('file', models.FileField(blank=True, max_length=512, null=True, upload_to=colander.core.models._get_upload_dir)),
                ('owner', models.ForeignKey(editable=False, help_text='Who owns this file.', on_delete=django.db.models.deletion.CASCADE, related_name='my_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColanderTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributors', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDump',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of your experiment.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date of your experiment.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Latest modification of your experiment.')),
                ('traffic_index', models.CharField(max_length=512)),
                ('extra_files', models.ManyToManyField(blank=True, related_name='extra_files_att', to='core.Attachment')),
                ('pcap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcap_file', to='core.attachment')),
                ('socket_trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socket_trace_file', to='core.attachment')),
                ('sslkeylog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of your experiment.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date of your experiment.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Latest modification of your experiment.')),
                ('name', models.CharField(default='', help_text='Give a meaningful name to your experiment.', max_length=512, verbose_name='name')),
                ('description', models.TextField(default='No description', help_text='Add more details about the project here.')),
                ('owner', models.ForeignKey(editable=False, help_text='Who owns the current experiment.', on_delete=django.db.models.deletion.CASCADE, related_name='my_experiments', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='core.colanderteam')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
