# Generated by Django 3.2.15 on 2022-11-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='involved_observables',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='core.Observable'),
        ),
    ]
