# Generated by Django 3.2.15 on 2022-09-24 18:18

import colander.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdump',
            name='traffic_index',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Elasticsearch index storing the network traffic analysis.'),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of this file.', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('EMAIL', 'Email file'), ('SAMPLE', 'Sample'), ('FORENSIC', 'Forensic dump'), ('PCAP', 'PCAP file'), ('SOCKET_TRACE', 'Socket activity trace'), ('ENCRYPTION_TRACE', 'Cryptographic activity trace'), ('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('WEB_PAGE', 'Web page'), ('SM_POST', 'Social media post'), ('REPORT', 'Report'), ('OTHER', 'Other type of file')], default='OTHER', max_length=16)),
                ('extension', models.CharField(blank=True, max_length=64, null=True)),
                ('original_name', models.CharField(blank=True, max_length=512, null=True)),
                ('stored_name', models.CharField(blank=True, max_length=512, null=True)),
                ('storage_name', models.CharField(blank=True, max_length=64, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=512, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=512, null=True)),
                ('detached_signature', models.TextField(blank=True, null=True)),
                ('md5', models.CharField(blank=True, max_length=65, null=True)),
                ('sha1', models.CharField(blank=True, max_length=65, null=True)),
                ('sha256', models.CharField(blank=True, max_length=65, null=True)),
                ('size_in_bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date of your experiment.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Latest modification of your experiment.')),
                ('file', models.FileField(blank=True, max_length=512, null=True, upload_to=colander.core.models._get_upload_dir)),
                ('owner', models.ForeignKey(editable=False, help_text='Who owns this file.', on_delete=django.db.models.deletion.CASCADE, related_name='my_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='networkdump',
            name='extra_files',
            field=models.ManyToManyField(blank=True, related_name='extra_files_att', to='core.Evidence'),
        ),
        migrations.AlterField(
            model_name='networkdump',
            name='pcap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcap_file', to='core.evidence'),
        ),
        migrations.AlterField(
            model_name='networkdump',
            name='socket_trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socket_trace_file', to='core.evidence'),
        ),
        migrations.AlterField(
            model_name='networkdump',
            name='sslkeylog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evidence'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
