# Generated by Django 3.2.15 on 2023-02-17 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='es_prefix',
            field=models.CharField(default='pw21cijhnmnn6m1l', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='first_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 17, 13, 4, 133020, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 17, 13, 4, 133044, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='es_prefix',
            field=models.CharField(default='jfu8hvzvenm6oaug', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='analysis_index',
            field=models.CharField(default='xk1g7cdf5yzwqanm', help_text='Elasticsearch index storing the analysis.', max_length=64),
        ),
    ]
