# Generated by Django 3.2.15 on 2022-11-09 16:33

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_event_involved_observables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonmodel',
            name='owner',
            field=models.ForeignKey(help_text='Who owns this object.', on_delete=django.db.models.deletion.CASCADE, related_name='core_commonmodel_related', related_query_name='core_commonmodels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detectionrule',
            name='detected_observables',
            field=models.ManyToManyField(to='core.Observable'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='involved_observables',
            field=models.ManyToManyField(related_name='events', to='core.Observable'),
        ),
    ]
