# Generated by Django 3.2.15 on 2022-09-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220924_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='status',
            new_name='type',
        ),
    ]
