# Generated by Django 3.2.15 on 2023-02-17 17:28

import colander.core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230217_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='first_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='es_prefix',
            field=models.CharField(default=colander.core.models._random_id, editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='analysis_index',
            field=models.CharField(default=colander.core.models._random_id, help_text='Elasticsearch index storing the analysis.', max_length=64),
        ),
    ]
