# Generated by Django 3.2.15 on 2023-02-17 17:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_auto_20230217_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observable',
            name='name',
            field=models.CharField(help_text='Value of this observable', max_length=512, verbose_name='Value'),
        ),
        migrations.CreateModel(
            name='EntityRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of this relation between two observables.', max_length=512)),
                ('obj_from_id', models.UUIDField()),
                ('obj_to_id', models.UUIDField()),
                ('obj_from_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obj_from_types', to='contenttypes.contenttype')),
                ('obj_to_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obj_to_types', to='contenttypes.contenttype')),
            ],
        ),
    ]
