# Generated by Django 3.2.15 on 2023-02-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230221_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityrelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Latest modification of this object.'),
        ),
    ]
