# Generated by Django 3.2.15 on 2023-03-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_entityrelation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirogueexperiment',
            name='aes_trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pirogue_aes_trace', to='core.artifact'),
        ),
    ]
