# Generated by Django 3.2.18 on 2023-03-09 18:16

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pirogueexperiment_aes_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityrelation',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
