# Generated by Django 3.2.18 on 2023-04-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_backendcredentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectionrule',
            old_name='detected_observables',
            new_name='targeted_observables',
        ),
        migrations.AddField(
            model_name='detectionrule',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
