# Generated by Django 3.2.15 on 2022-12-01 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221201_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='first_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 20, 10, 53, 454642, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 20, 10, 53, 454671, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
