# Generated by Django 3.2.18 on 2023-04-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230409_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrule',
            name='targeted_observables',
            field=models.ManyToManyField(blank=True, null=True, to='core.Observable'),
        ),
    ]
