# Generated by Django 3.2.18 on 2023-04-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_detectionrule_targeted_observables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='documentation',
            field=models.TextField(blank=True, help_text='Case documentation.', null=True),
        ),
    ]
