# Generated by Django 3.2.18 on 2023-04-18 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_alter_case_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date of this object.')),
                ('eof', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('size', models.IntegerField(default=0)),
                ('next_addr', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='CREATED', max_length=16)),
                ('chunks', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
