# Generated by Django 3.2.18 on 2023-04-19 13:50

import colander.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_uploadrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=colander.core.models._get_evidence_upload_dir),
        ),
    ]
