# Generated by Django 3.2.18 on 2023-04-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_artifact_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrequest',
            name='target_artifact_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
