# Generated by Django 3.2.18 on 2023-04-20 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230420_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='extracted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='operated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='core.actor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='detected_by',
            field=models.ForeignKey(blank=True, help_text='Select the rule which has detected this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.detectionrule'),
        ),
        migrations.AlterField(
            model_name='event',
            name='extracted_from',
            field=models.ForeignKey(blank=True, help_text='Select the artifact from which this event was extracted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.artifact'),
        ),
        migrations.AlterField(
            model_name='event',
            name='observed_on',
            field=models.ForeignKey(blank=True, help_text='Select the device on which this event was observed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.device'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='associated_threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observables', to='core.threat'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='extracted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observables', to='core.artifact'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='operated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observables', to='core.actor'),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='aes_trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pirogue_aes_trace', to='core.artifact'),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='pcap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pirogue_dump_pcap_file', to='core.artifact'),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='screencast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pirogue_dump_screencast', to='core.artifact'),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='socket_trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pirogue_dump_socket_trace_file', to='core.artifact'),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='sslkeylog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pirogue_dump_ssl_keys', to='core.artifact'),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='target_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pirogue_dump_artifact', to='core.artifact'),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='target_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pirogue_dump_device', to='core.device'),
        ),
    ]
