# Generated by Django 3.2.18 on 2023-04-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230420_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='pcap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pirogue_dump_pcap_file', to='core.artifact'),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='socket_trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pirogue_dump_socket_trace_file', to='core.artifact'),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='sslkeylog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pirogue_dump_ssl_keys', to='core.artifact'),
        ),
    ]
