# Generated by Django 3.2.18 on 2023-05-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230421_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='colanderteam',
            name='name',
            field=models.CharField(default='', help_text='Give a meaningful name to this type of artifact.', max_length=512, verbose_name='name'),
        ),
    ]
