# Generated by Django 3.2.15 on 2023-01-13 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230113_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiRogueExperiment',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.commonmodel')),
                ('name', models.CharField(max_length=512)),
                ('traffic_index', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Elasticsearch index storing the network traffic.')),
                ('analysis_index', models.CharField(default='s43yaqj28qrhi4k0', help_text='Elasticsearch index storing the analysis.', max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.commonmodel', models.Model),
        ),
        migrations.AlterField(
            model_name='case',
            name='es_prefix',
            field=models.CharField(default='91ju4fub4oha37zx', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='first_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 16, 41, 49, 33803, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 16, 41, 49, 33828, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='es_prefix',
            field=models.CharField(default='051qhthuohqwgdzr', editable=False, max_length=16),
        ),
        migrations.DeleteModel(
            name='PiRogueDump',
        ),
        migrations.AddField(
            model_name='pirogueexperiment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_pirogueexperiment_related', related_query_name='core_pirogueexperiments', to='core.case'),
        ),
        migrations.AddField(
            model_name='pirogueexperiment',
            name='extra_files',
            field=models.ManyToManyField(blank=True, related_name='extra_files_att', to='core.Artifact'),
        ),
        migrations.AddField(
            model_name='pirogueexperiment',
            name='pcap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pirogue_dump_pcap_file', to='core.artifact'),
        ),
        migrations.AddField(
            model_name='pirogueexperiment',
            name='socket_trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pirogue_dump_socket_trace_file', to='core.artifact'),
        ),
        migrations.AddField(
            model_name='pirogueexperiment',
            name='sslkeylog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pirogue_dump_ssl_keys', to='core.artifact'),
        ),
        migrations.AddField(
            model_name='pirogueexperiment',
            name='target_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pirogue_dump_artifact', to='core.artifact'),
        ),
        migrations.AddField(
            model_name='pirogueexperiment',
            name='target_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pirogue_dump_device', to='core.device'),
        ),
    ]
