# Generated by Django 3.2.18 on 2023-05-02 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_colanderteam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colanderteam',
            name='contributors',
            field=models.ManyToManyField(related_name='teams_as_contrib', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='colanderteam',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_as_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
