# Generated by Django 3.2.15 on 2023-01-26 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20230113_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pirogueexperiment',
            options={'verbose_name': 'PiRogue experiment'},
        ),
        migrations.AddField(
            model_name='case',
            name='signing_key',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='verify_key',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='es_prefix',
            field=models.CharField(default='5ehh871j3h26sev2', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='first_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 14, 24, 18, 157923, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 14, 24, 18, 157949, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='es_prefix',
            field=models.CharField(default='50x41c8pd3gxo52j', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='analysis_index',
            field=models.CharField(default='vk4wejkpzsd1exag', help_text='Elasticsearch index storing the analysis.', max_length=64),
        ),
    ]
