# Generated by Django 3.2.15 on 2023-01-30 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230126_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='es_prefix',
            field=models.CharField(default='u88odel198xjb8ts', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='case',
            name='signing_key',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='verify_key',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='first_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 19, 24, 51, 474599, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 19, 24, 51, 474628, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='es_prefix',
            field=models.CharField(default='ls7rrxpafq3lzycw', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='analysis_index',
            field=models.CharField(default='1eqplexbrqi7590r', help_text='Elasticsearch index storing the analysis.', max_length=64),
        ),
    ]
