# Generated by Django 3.2.18 on 2023-05-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230502_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_cases', to='core.ColanderTeam'),
        ),
    ]
