# Generated by Django 3.2.18 on 2023-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_case_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='case',
            name='team',
        ),
        migrations.AddField(
            model_name='case',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='cases', to='core.ColanderTeam'),
        ),
    ]
