# Generated by Django 3.2.18 on 2023-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20230502_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colanderteam',
            name='name',
            field=models.CharField(default='', help_text='Give a meaningful name to this team.', max_length=512, verbose_name='name'),
        ),
    ]
