# Generated by Django 3.2.15 on 2023-02-10 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20230208_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='documentation',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='es_prefix',
            field=models.CharField(default='ox8av09zs2xn9z4o', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='first_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 14, 41, 32, 475400, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 14, 41, 32, 475448, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='es_prefix',
            field=models.CharField(default='ggtqglwtqgmf5p30', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='pirogueexperiment',
            name='analysis_index',
            field=models.CharField(default='z8ax7hyx6n1geo86', help_text='Elasticsearch index storing the analysis.', max_length=64),
        ),
    ]
