# Generated by Django 3.2.18 on 2023-06-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20230601_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionruleoutgoingfeed',
            name='content_type',
            field=models.CharField(max_length=512),
        ),
    ]
