# Generated by Django 3.2.18 on 2023-06-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_detectionruleoutgoingfeed_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionruleoutgoingfeed',
            name='content_type',
            field=models.CharField(choices=[('SURICATA', 'Suricata rule'), ('YARA', 'Yara rule')], max_length=512),
        ),
    ]
