# Generated by Django 3.2.18 on 2023-06-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0027_alter_detectionruleoutgoingfeed_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityoutgoingfeed',
            name='content_type',
            field=models.ManyToManyField(choices=[(32, 'Actor'), (33, 'Artifact'), (35, 'Device'), (36, 'Observable'), (40, 'Threat')], related_name='entity_out_feed_types', to='contenttypes.ContentType'),
        ),
    ]
