# Generated by Django 3.2.18 on 2023-06-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0028_alter_entityoutgoingfeed_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityoutgoingfeed',
            name='content_type',
            field=models.ManyToManyField(limit_choices_to={'model__in': ['observable', 'actor']}, related_name='entity_out_feed_types', to='contenttypes.ContentType'),
        ),
    ]
