# Generated by Django 3.2.18 on 2023-06-01 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20230601_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionruleoutgoingfeed',
            name='content_type',
            field=models.CharField(choices=[(uuid.UUID('8a9537cc-1bbb-4d8e-8a0f-b8bb08c4cb20'), 'Suricata rule'), (uuid.UUID('07ecd6d3-e89e-4f9a-a794-06b7692f22c1'), 'Yara rule')], max_length=512),
        ),
        migrations.AlterField(
            model_name='outgoingfeed',
            name='max_pap',
            field=models.CharField(choices=[('RED', 'RED'), ('AMBER', 'AMBER'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE')], default='WHITE', help_text='Permissible Actions Protocol, designed to indicate how the received information can be used.', max_length=6, verbose_name='Maximum PAP level of exported data'),
        ),
        migrations.AlterField(
            model_name='outgoingfeed',
            name='max_tlp',
            field=models.CharField(choices=[('RED', 'RED'), ('AMBER', 'AMBER'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE')], default='WHITE', help_text='Traffic Light Protocol, designed to indicate the sharing boundaries to be applied.', max_length=6, verbose_name='Maximum TLP level of exported data'),
        ),
    ]
