# Generated by Django 3.2.18 on 2023-06-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20230601_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionruleoutgoingfeed',
            name='content_type',
            field=models.CharField(choices=[('8a9537cc-1bbb-4d8e-8a0f-b8bb08c4cb20', 'Suricata rule'), ('07ecd6d3-e89e-4f9a-a794-06b7692f22c1', 'Yara rule')], max_length=512),
        ),
    ]
