# Generated by Django 3.2.18 on 2023-06-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_detectionruleoutgoingfeed_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionruleoutgoingfeed',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detectionruletype'),
        ),
    ]
