# Generated by Django 3.2.18 on 2023-06-02 08:57

import colander.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0033_alter_detectionruleoutgoingfeed_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityoutgoingfeed',
            name='content_type',
            field=models.ManyToManyField(limit_choices_to={'app_label': 'core', 'model__in': ['actor', 'artifact', 'device', 'observable', 'threat']}, related_name='entity_out_feed_types', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='outgoingfeed',
            name='secret',
            field=models.CharField(default=colander.core.models._random_id, help_text='Feeds are protected by a secret. You can reset it at anytime invalidating the previous one.', max_length=512),
        ),
    ]
