# Generated by Django 3.2.18 on 2023-06-16 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20230603_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFragmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_name', models.CharField(editable=False, max_length=32)),
                ('name', models.CharField(default='', help_text='Give a meaningful name to this type of artifact.', max_length=512, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Add more details about it.', null=True)),
                ('svg_icon', models.TextField(blank=True, null=True)),
                ('nf_icon', models.CharField(blank=True, max_length=256, null=True)),
                ('stix2_type', models.CharField(blank=True, max_length=256, null=True)),
                ('stix2_value_field_name', models.CharField(blank=True, max_length=256, null=True)),
                ('stix2_pattern', models.CharField(blank=True, max_length=256, null=True)),
                ('stix2_pattern_type', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataFragment',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.entity')),
                ('name', models.CharField(help_text='Name of this fragment of data.', max_length=512)),
                ('content', models.TextField()),
                ('extracted_from', models.ForeignKey(blank=True, help_text='Select the artifact from which this fragment of data was extracted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_fragments', to='core.artifact')),
                ('type', models.ForeignKey(help_text='Type of this fragment of data.', on_delete=django.db.models.deletion.CASCADE, to='core.datafragmenttype')),
            ],
            bases=('core.entity',),
        ),
    ]
