# Generated by Django 3.2.18 on 2023-07-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_datafragment_datafragmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='overrides',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
