# Generated by Django 3.2.18 on 2023-09-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_case_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(help_text='Add more details about the case here.'),
        ),
    ]
