# Generated by Django 3.2.18 on 2023-09-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_case_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='pap',
            field=models.CharField(choices=[('RED', 'RED'), ('AMBER', 'AMBER'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE')], default='WHITE', help_text='Permissible Actions Protocol, designed to indicate how the received information can be used.', max_length=6, verbose_name='Maximum PAP level of exported data'),
        ),
        migrations.AddField(
            model_name='case',
            name='tlp',
            field=models.CharField(choices=[('RED', 'RED'), ('AMBER', 'AMBER'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE')], default='WHITE', help_text='Traffic Light Protocol, designed to indicate the sharing boundaries to be applied.', max_length=6, verbose_name='Maximum TLP level of exported data'),
        ),
    ]
