# Generated by Django 4.2.8 on 2024-03-03 13:21

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0041_alter_event_involved_observables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True,
                help_text="Add custom attributes to this artifact.",
                null=True,
                verbose_name="Custom attributes",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True,
                help_text="Add custom attributes to this device.",
                null=True,
                verbose_name="Custom attributes",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="core.case",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="owner",
            field=models.ForeignKey(
                help_text="Who owns this object.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="entityrelation",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="core.case",
            ),
        ),
        migrations.AlterField(
            model_name="entityrelation",
            name="owner",
            field=models.ForeignKey(
                help_text="Who owns this object.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True,
                help_text="Add custom attributes to this event.",
                null=True,
                verbose_name="Custom attributes",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="first_seen",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="First time you observed this event.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="last_seen",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Most recent time you observed this event.",
            ),
        ),
        migrations.AlterField(
            model_name="observable",
            name="attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True,
                help_text="Add custom attributes to this observable.",
                null=True,
                verbose_name="Custom attributes",
            ),
        ),
        migrations.AlterField(
            model_name="observable",
            name="classification",
            field=models.CharField(
                blank=True,
                help_text="Optional field containing an arbitrary string of your choice.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="outgoingfeed",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="core.case",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingfeed",
            name="owner",
            field=models.ForeignKey(
                help_text="Who owns this feed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
