# Generated by Django 4.2.8 on 2024-03-03 13:34

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_alter_artifact_attributes_alter_device_attributes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actortype",
            name="default_attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True, verbose_name="Default attributes"
            ),
        ),
        migrations.AddField(
            model_name="artifacttype",
            name="default_attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True, verbose_name="Default attributes"
            ),
        ),
        migrations.AddField(
            model_name="datafragmenttype",
            name="default_attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True, verbose_name="Default attributes"
            ),
        ),
        migrations.AddField(
            model_name="detectionruletype",
            name="default_attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True, verbose_name="Default attributes"
            ),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="default_attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True, verbose_name="Default attributes"
            ),
        ),
        migrations.AddField(
            model_name="eventtype",
            name="default_attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True, verbose_name="Default attributes"
            ),
        ),
        migrations.AddField(
            model_name="observabletype",
            name="default_attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True, verbose_name="Default attributes"
            ),
        ),
        migrations.AddField(
            model_name="threattype",
            name="default_attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True, verbose_name="Default attributes"
            ),
        ),
    ]
