# Generated by Django 4.2.8 on 2024-08-13 15:57

import colander.core.models
from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0043_actortype_default_attributes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DroppedFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dropped_at", models.DateTimeField(auto_now_add=True, help_text="Drop date of this file.")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to=colander.core.models._get_dropped_file_upload_dir,
                    ),
                ),
                (
                    "attributes",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True,
                        help_text="Custom attributes related to this dropped file.",
                        null=True,
                        verbose_name="Custom attributes",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated case of this dropped file.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dropped_files",
                        to="core.case",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropped_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
