# Generated by Django 4.2.8 on 2024-12-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_droppedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="droppedfile",
            name="filename",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="droppedfile",
            name="name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
