# Generated by Django 4.2.8 on 2024-12-05 09:01

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_droppedfile_filename_droppedfile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="actortype",
            name="type_hints",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AddField(
            model_name="artifacttype",
            name="type_hints",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AddField(
            model_name="datafragmenttype",
            name="type_hints",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AddField(
            model_name="detectionruletype",
            name="type_hints",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="type_hints",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AddField(
            model_name="eventtype",
            name="type_hints",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AddField(
            model_name="observabletype",
            name="type_hints",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AddField(
            model_name="threattype",
            name="type_hints",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name="Type hints"),
        ),
    ]
