# Generated by Django 4.2.8 on 2024-12-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_actortype_type_hints_artifacttype_type_hints_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actortype",
            name="type_hints",
            field=models.JSONField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AlterField(
            model_name="artifacttype",
            name="type_hints",
            field=models.JSONField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AlterField(
            model_name="datafragmenttype",
            name="type_hints",
            field=models.JSONField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AlterField(
            model_name="detectionruletype",
            name="type_hints",
            field=models.JSONField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="type_hints",
            field=models.JSONField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="type_hints",
            field=models.JSONField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AlterField(
            model_name="observabletype",
            name="type_hints",
            field=models.JSONField(blank=True, null=True, verbose_name="Type hints"),
        ),
        migrations.AlterField(
            model_name="threattype",
            name="type_hints",
            field=models.JSONField(blank=True, null=True, verbose_name="Type hints"),
        ),
    ]
