# Generated by Django 4.2.8 on 2024-12-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_droppedfile_target_artifact_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="droppedfile",
            name="mime_type",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
