# Generated by Django 4.2.8 on 2025-02-25 17:51

import colander.core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_entity_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="thumbnail",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to=colander.core.models._get_entity_thumbnails_storage_dir,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["png", "jpg", "jpeg"])],
            ),
        ),
    ]
