# Generated by Django 4.2.20 on 2025-05-22 15:44

import colander.core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_alter_entity_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="parent_case",
            field=models.ForeignKey(
                blank=True,
                help_text="Make this case a sub-case of another one.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_cases",
                to="core.case",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="thumbnail",
            field=colander.core.models.OverwritableFileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to=colander.core.models._get_entity_thumbnails_storage_dir,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["png", "jpg", "jpeg"])],
            ),
        ),
        migrations.AlterField(
            model_name="subgraph",
            name="thumbnail",
            field=colander.core.models.OverwritableFileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to=colander.core.models._get_subgraph_thumbnails_storage_dir,
            ),
        ),
    ]
