# Generated by Django 4.2.20 on 2025-10-06 13:35

import colander.core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_alter_case_parent_case_alter_entity_thumbnail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("UNSPECIFIED", "UNSPECIFIED"), ("CASE", "CASE")],
                        default="UNSPECIFIED",
                        help_text="Export type.",
                        max_length=16,
                        verbose_name="Export type",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True, help_text="Export request date.")),
                ("done_at", models.DateTimeField(editable=False, help_text="Export done date.")),
                (
                    "file",
                    models.FileField(
                        blank=True, max_length=512, null=True, upload_to=colander.core.models._get_export_file_dir
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="core.case",
                    ),
                ),
            ],
        ),
    ]
