# Generated by Django 4.2.20 on 2025-10-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0055_archiveexport"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("INTERNAL", "INTERNAL"), ("MAIL", "MAIL")],
                        default="INTERNAL",
                        help_text="Notification type.",
                        max_length=16,
                        verbose_name="Notification type",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True, help_text="Notification request date.")),
                ("processed_at", models.DateTimeField(editable=False, help_text="Notification process date.")),
                ("success", models.BooleanField(editable=False, help_text="Notification process result success.")),
                (
                    "template_path",
                    models.CharField(
                        default="",
                        help_text="Internal template path used to generate the notification content with the given context.",
                        max_length=512,
                        verbose_name="template_path",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict, verbose_name="Template context used to generate the notification content."
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
