# Generated by Django 4.2.20 on 2025-10-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_notificationmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actortype",
            old_name="svg_icon",
            new_name="icon",
        ),
        migrations.RenameField(
            model_name="artifacttype",
            old_name="svg_icon",
            new_name="icon",
        ),
        migrations.RenameField(
            model_name="datafragmenttype",
            old_name="svg_icon",
            new_name="icon",
        ),
        migrations.RenameField(
            model_name="detectionruletype",
            old_name="svg_icon",
            new_name="icon",
        ),
        migrations.RenameField(
            model_name="devicetype",
            old_name="svg_icon",
            new_name="icon",
        ),
        migrations.RenameField(
            model_name="eventtype",
            old_name="svg_icon",
            new_name="icon",
        ),
        migrations.RenameField(
            model_name="observabletype",
            old_name="svg_icon",
            new_name="icon",
        ),
        migrations.RenameField(
            model_name="threattype",
            old_name="svg_icon",
            new_name="icon",
        ),
        migrations.RemoveField(
            model_name="actortype",
            name="stix2_pattern",
        ),
        migrations.RemoveField(
            model_name="actortype",
            name="stix2_pattern_type",
        ),
        migrations.RemoveField(
            model_name="actortype",
            name="stix2_type",
        ),
        migrations.RemoveField(
            model_name="actortype",
            name="stix2_value_field_name",
        ),
        migrations.RemoveField(
            model_name="artifacttype",
            name="stix2_pattern",
        ),
        migrations.RemoveField(
            model_name="artifacttype",
            name="stix2_pattern_type",
        ),
        migrations.RemoveField(
            model_name="artifacttype",
            name="stix2_type",
        ),
        migrations.RemoveField(
            model_name="artifacttype",
            name="stix2_value_field_name",
        ),
        migrations.RemoveField(
            model_name="datafragmenttype",
            name="stix2_pattern",
        ),
        migrations.RemoveField(
            model_name="datafragmenttype",
            name="stix2_pattern_type",
        ),
        migrations.RemoveField(
            model_name="datafragmenttype",
            name="stix2_type",
        ),
        migrations.RemoveField(
            model_name="datafragmenttype",
            name="stix2_value_field_name",
        ),
        migrations.RemoveField(
            model_name="detectionruletype",
            name="stix2_pattern",
        ),
        migrations.RemoveField(
            model_name="detectionruletype",
            name="stix2_pattern_type",
        ),
        migrations.RemoveField(
            model_name="detectionruletype",
            name="stix2_type",
        ),
        migrations.RemoveField(
            model_name="detectionruletype",
            name="stix2_value_field_name",
        ),
        migrations.RemoveField(
            model_name="devicetype",
            name="stix2_pattern",
        ),
        migrations.RemoveField(
            model_name="devicetype",
            name="stix2_pattern_type",
        ),
        migrations.RemoveField(
            model_name="devicetype",
            name="stix2_type",
        ),
        migrations.RemoveField(
            model_name="devicetype",
            name="stix2_value_field_name",
        ),
        migrations.RemoveField(
            model_name="eventtype",
            name="stix2_pattern",
        ),
        migrations.RemoveField(
            model_name="eventtype",
            name="stix2_pattern_type",
        ),
        migrations.RemoveField(
            model_name="eventtype",
            name="stix2_type",
        ),
        migrations.RemoveField(
            model_name="eventtype",
            name="stix2_value_field_name",
        ),
        migrations.RemoveField(
            model_name="observabletype",
            name="stix2_pattern",
        ),
        migrations.RemoveField(
            model_name="observabletype",
            name="stix2_pattern_type",
        ),
        migrations.RemoveField(
            model_name="observabletype",
            name="stix2_type",
        ),
        migrations.RemoveField(
            model_name="observabletype",
            name="stix2_value_field_name",
        ),
        migrations.RemoveField(
            model_name="threattype",
            name="stix2_pattern",
        ),
        migrations.RemoveField(
            model_name="threattype",
            name="stix2_pattern_type",
        ),
        migrations.RemoveField(
            model_name="threattype",
            name="stix2_type",
        ),
        migrations.RemoveField(
            model_name="threattype",
            name="stix2_value_field_name",
        ),
        migrations.AddField(
            model_name="actortype",
            name="regex",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actortype",
            name="value_example",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artifacttype",
            name="regex",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artifacttype",
            name="value_example",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datafragmenttype",
            name="regex",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datafragmenttype",
            name="value_example",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detectionruletype",
            name="regex",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detectionruletype",
            name="value_example",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="regex",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="value_example",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventtype",
            name="regex",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventtype",
            name="value_example",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observabletype",
            name="regex",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observabletype",
            name="value_example",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="threattype",
            name="regex",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="threattype",
            name="value_example",
            field=models.TextField(blank=True, null=True),
        ),
    ]
