# Generated by Django 4.2.20 on 2025-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_rename_svg_icon_actortype_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityoutgoingfeed",
            name="misp_org_id",
            field=models.CharField(
                blank=True,
                help_text="UUID of your organization as set in MISP. Orgc of your events will be set accordingly.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entityoutgoingfeed",
            name="misp_org_name",
            field=models.CharField(
                blank=True,
                help_text="Name of your organization as set in MISP. Orgc of your events will be set accordingly.",
                max_length=512,
                null=True,
            ),
        ),
    ]
