# Generated by Django 4.2.20 on 2025-10-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_entityoutgoingfeed_misp_org_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attributed_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the actor attributed to this event.",
                null=True,
                related_name="attributed_events",
                to="core.actor",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="target",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the actor targeted during this event.",
                null=True,
                related_name="targeted_events",
                to="core.actor",
            ),
        ),
        migrations.AlterField(
            model_name="entityoutgoingfeed",
            name="misp_org_id",
            field=models.CharField(
                blank=True,
                help_text="UUID of your organization as set in MISP. The Orgc UUID of your events will be set accordingly. Must be set to make your feed available in MISP format.",
                max_length=512,
                null=True,
                verbose_name="MISP: UUID of your organization",
            ),
        ),
        migrations.AlterField(
            model_name="entityoutgoingfeed",
            name="misp_org_name",
            field=models.CharField(
                blank=True,
                help_text="Name of your organization as set in MISP. The Orgc name of your events will be set accordingly. Must be set to make your feed available in MISP format.",
                max_length=512,
                null=True,
                verbose_name="MISP: name of your organization",
            ),
        ),
    ]
