# Generated by Django 4.2.20 on 2025-10-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_event_attributed_to_event_target_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="attributed_to",
        ),
        migrations.RemoveField(
            model_name="event",
            name="target",
        ),
        migrations.AddField(
            model_name="event",
            name="attributed_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the actor attributed to this event.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attributed_events",
                to="core.actor",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="target",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the actor targeted during this event.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_events",
                to="core.actor",
            ),
        ),
    ]
