# Generated by Django 4.2.20 on 2025-10-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0060_remove_event_attributed_to_remove_event_target_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityoutgoingfeed",
            name="content_type",
            field=models.ManyToManyField(
                limit_choices_to={
                    "app_label": "core",
                    "model__in": [
                        "actor",
                        "artifact",
                        "datafragment",
                        "detectionrule",
                        "device",
                        "observable",
                        "threat",
                    ],
                },
                related_name="entity_out_feed_types",
                to="contenttypes.contenttype",
            ),
        ),
    ]
