# Generated by Django 4.2.20 on 2025-10-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0061_alter_entityoutgoingfeed_content_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DetectionRuleOutgoingFeed",
            new_name="DetectionRuleExportFeed",
        ),
        migrations.RenameModel(
            old_name="EntityOutgoingFeed",
            new_name="EntityExportFeed",
        ),
    ]
