# Generated by Django 4.2.20 on 2025-10-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_rename_detectionruleoutgoingfeed_detectionruleexportfeed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="verify_key",
            new_name="public_key",
        ),
    ]
