# Generated by Django 4.2.20 on 2025-11-17 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0063_rename_verify_key_case_public_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityexportfeed",
            name="content_type",
            field=models.ManyToManyField(
                limit_choices_to={
                    "app_label": "core",
                    "model__in": [
                        "actor",
                        "artifact",
                        "datafragment",
                        "detectionrule",
                        "device",
                        "event",
                        "observable",
                        "threat",
                    ],
                },
                related_name="entity_out_feed_types",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="FeedTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Add more details about this object.", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Creation date of this object.")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Latest modification of this object.")),
                ("content", models.TextField()),
                ("in_errors", models.BooleanField(default=False, editable=False)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("Cases", "Cases"), ("Teams", "Teams"), ("Public", "Public")],
                        default="Teams",
                        help_text="The visibility of the template, either limited to the case, to the teams or public",
                        max_length=6,
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="core.case",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Who owns this object.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        help_text="Share this template with the selected teams. Press ctrl to select/deselect teams.",
                        related_name="templates",
                        to="core.colanderteam",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
