# Generated by Django 4.2.20 on 2025-11-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_alter_entityexportfeed_content_type_feedtemplate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedtemplate",
            old_name="in_errors",
            new_name="in_error",
        ),
        migrations.AlterField(
            model_name="feedtemplate",
            name="teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Share this template with the selected teams. Press ctrl to select/deselect teams.",
                related_name="templates",
                to="core.colanderteam",
            ),
        ),
    ]
