# Generated by Django 4.2.20 on 2025-11-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_rename_in_errors_feedtemplate_in_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedtemplate",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="core.case",
            ),
        ),
        migrations.AlterField(
            model_name="feedtemplate",
            name="visibility",
            field=models.CharField(
                choices=[("Cases", "Cases"), ("Public", "Public")],
                default="Cases",
                help_text="The visibility of the template, either limited to the case, to the teams or public",
                max_length=6,
                verbose_name="Visibility",
            ),
        ),
        migrations.CreateModel(
            name="CustomExportFeed",
            fields=[
                (
                    "outgoingfeed_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.outgoingfeed",
                    ),
                ),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.feedtemplate")),
            ],
            bases=("core.outgoingfeed",),
        ),
    ]
