# Generated by Django 4.2.20 on 2025-11-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_alter_feedtemplate_case_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadrequest",
            old_name="target_artifact_id",
            new_name="target_entity_id",
        ),
        migrations.AlterField(
            model_name="archiveexport",
            name="done_at",
            field=models.DateTimeField(blank=True, editable=False, help_text="Export done date.", null=True),
        ),
        migrations.AlterField(
            model_name="notificationmessage",
            name="processed_at",
            field=models.DateTimeField(blank=True, editable=False, help_text="Notification process date.", null=True),
        ),
        migrations.AlterField(
            model_name="notificationmessage",
            name="success",
            field=models.BooleanField(default=False, editable=False, help_text="Notification process result success."),
        ),
    ]
