# Generated by Django 4.2.20 on 2026-01-15 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0067_rename_target_artifact_id_uploadrequest_target_entity_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PiRogueCredentials",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "friendly_name",
                    models.CharField(
                        blank=True,
                        help_text="A friendly name only displayed in Colander. If empty, this PiRogue will be displayed with its host value.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="Can be FQDN or IP address (for non publicly visible PiRogue).", max_length=256
                    ),
                ),
                ("port", models.IntegerField(default=50051)),
                (
                    "token",
                    models.CharField(help_text="Private access token (retrieved on your PiRogue).", max_length=512),
                ),
                (
                    "has_public_visibility",
                    models.BooleanField(help_text="Does this PiRogue has public access enabled ?"),
                ),
                (
                    "certificate",
                    models.CharField(
                        blank=True,
                        help_text="Certificate must be provided if PiRogue public access has not been enabled.",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "PiRogue Credentials",
                "verbose_name_plural": "PiRogue Credentials",
            },
        ),
        migrations.AlterField(
            model_name="entityexportfeed",
            name="content_type",
            field=models.ManyToManyField(
                limit_choices_to={
                    "app_label": "core",
                    "model__in": [
                        "actor",
                        "artifact",
                        "datafragment",
                        "detectionrule",
                        "device",
                        "observable",
                        "threat",
                    ],
                },
                related_name="entity_out_feed_types",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="PiRogueStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True, help_text="Reported date of this status.")),
                ("success", models.BooleanField(default=False, help_text="Does this status retrieval has succeed ?")),
                (
                    "error",
                    models.CharField(
                        blank=True, help_text="Error detail if status retrieval failed.", max_length=4096, null=True
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                (
                    "pirogue_credentials",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pirogue_aes_trace",
                        to="core.piroguecredentials",
                    ),
                ),
            ],
            options={
                "verbose_name": "PiRogue Status",
                "verbose_name_plural": "PiRogue Status",
            },
        ),
    ]
