# Generated by Django 4.2.20 on 2026-02-18 16:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0068_piroguecredentials_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piroguecredentials",
            name="certificate",
            field=models.CharField(
                blank=True,
                help_text="Certificate must be provided if the PiRogue is not accessible on the Internet.",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="piroguecredentials",
            name="has_public_visibility",
            field=models.BooleanField(help_text="Is this PiRogue accessible on the Internet?"),
        ),
        migrations.AlterField(
            model_name="piroguecredentials",
            name="host",
            field=models.CharField(help_text="Can be a FQDN or an IP address.", max_length=256),
        ),
        migrations.AlterField(
            model_name="piroguecredentials",
            name="token",
            field=models.CharField(help_text="Private access token (generated on your PiRogue).", max_length=512),
        ),
        migrations.AlterField(
            model_name="piroguestatus",
            name="success",
            field=models.BooleanField(default=False, help_text="Does this status retrieval has succeed?"),
        )
    ]
