# Generated by Django 4.2.20 on 2026-02-18 16:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0069_alter_piroguecredentials_certificate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceMonitoring",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Add more details about this object.", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("peer_id", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Not started"), (1, "In progress"), (2, "Finished"), (-1, "Failed")],
                        default=0,
                        editable=False,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=1,
                        help_text="Number of days this monitoring will be active (between 1 and 14 days).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="core.case",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="The device to be monitored.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.device",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pirogue",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.piroguecredentials"),
                ),
            ],
            options={
                "verbose_name": "Device monitoring",
                "unique_together": {("device", "pirogue", "peer_id")},
            },
        ),
    ]
