# Generated by Django 4.2.20 on 2026-02-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_devicemonitoring"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkDPI",
            fields=[
                ("id", models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ("time", models.DateTimeField(editable=False)),
                ("timestamp", models.FloatField(editable=False)),
                ("community_id", models.CharField(db_index=True, editable=False, max_length=255)),
                ("community_id_b64", models.CharField(editable=False, max_length=255)),
                ("risk", models.IntegerField(default=0, editable=False)),
                ("bidirectional_duration_ms", models.IntegerField(default=0, editable=False)),
                ("bidirectional_bytes", models.IntegerField(default=0, editable=False)),
                ("bidirectional_packets", models.IntegerField(default=0, editable=False)),
                ("protocol", models.CharField(default="unknown", editable=False, max_length=255)),
                ("protocol_number", models.IntegerField(default=0, editable=False)),
                ("ip_version", models.IntegerField(default=4, editable=False)),
                ("src_ip", models.CharField(editable=False, max_length=255)),
                ("src_mac", models.CharField(editable=False, max_length=255)),
                ("src_port", models.IntegerField(default=0, editable=False)),
                ("dst_ip", models.CharField(editable=False, max_length=255)),
                ("dst_mac", models.CharField(editable=False, max_length=255)),
                ("dst_port", models.IntegerField(default=0, editable=False)),
                ("dst2src_bytes", models.IntegerField(default=0, editable=False)),
                ("src2dst_bytes", models.IntegerField(default=0, editable=False)),
                ("application_name", models.CharField(default="unknown", editable=False, max_length=512)),
                ("application_category_name", models.CharField(default="unknown", editable=False, max_length=512)),
                ("requested_server_name", models.CharField(default="unknown", editable=False, max_length=512)),
                ("client_fingerprint", models.CharField(default="unknown", editable=False, max_length=512)),
                ("server_fingerprint", models.CharField(default="unknown", editable=False, max_length=512)),
                ("enrichment", models.JSONField(default=dict)),
                ("extra", models.JSONField(default=dict)),
                (
                    "device",
                    models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to="core.device"),
                ),
            ],
            options={
                "verbose_name": "Network DPI",
                "verbose_name_plural": "Network DPI",
            },
        ),
        migrations.CreateModel(
            name="NetworkAlert",
            fields=[
                ("id", models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ("time", models.DateTimeField(editable=False)),
                ("timestamp", models.FloatField(editable=False)),
                ("community_id", models.CharField(db_index=True, editable=False, max_length=255)),
                ("community_id_b64", models.CharField(editable=False, max_length=255)),
                ("flow_id", models.IntegerField(default=0, editable=False)),
                ("src_ip", models.CharField(editable=False, max_length=255)),
                ("src_port", models.IntegerField(default=0, editable=False)),
                ("dst_ip", models.CharField(editable=False, max_length=255)),
                ("dst_port", models.IntegerField(default=0, editable=False)),
                ("protocol", models.CharField(default="unknown", editable=False, max_length=255)),
                ("app_proto", models.CharField(default="unknown", editable=False, max_length=255)),
                ("rule", models.TextField(default="")),
                ("category", models.TextField(default="")),
                ("signature", models.TextField(default="")),
                ("severity", models.IntegerField(default=5, editable=False)),
                ("action", models.CharField(editable=False, max_length=255)),
                ("signature_id", models.IntegerField(default=0, editable=False)),
                ("gid", models.IntegerField(default=0, editable=False)),
                ("rev", models.IntegerField(default=0, editable=False)),
                ("enrichment", models.JSONField(default=dict)),
                ("extra", models.JSONField(default=dict)),
                (
                    "device",
                    models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to="core.device"),
                ),
            ],
            options={
                "verbose_name": "Network alert",
                "verbose_name_plural": "Network alerts",
            },
        ),
    ]
