# Generated by Django 4.2.20 on 2026-02-18 17:56

import colander.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_networkdpi_networkalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemonitoring",
            name="authentication_token",
            field=models.CharField(default=colander.core.models._generate_token, editable=False, max_length=128),
        ),
    ]
