# Generated by Django 4.2.20 on 2026-02-20 15:54

import colander.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_devicemonitoring_authentication_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networkalert",
            options={"ordering": ["-time"], "verbose_name": "Network alert", "verbose_name_plural": "Network alerts"},
        ),
        migrations.AlterModelOptions(
            name="networkdpi",
            options={"ordering": ["-time"], "verbose_name": "Network DPI", "verbose_name_plural": "Network DPI"},
        ),
        migrations.AlterField(
            model_name="devicemonitoring",
            name="authentication_token",
            field=models.CharField(default=colander.core.models._generate_token, max_length=128),
        ),
        migrations.AlterField(
            model_name="devicemonitoring",
            name="description",
            field=models.TextField(blank=True, help_text="Add more details.", null=True),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="action",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="app_proto",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="community_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="community_id_b64",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="device",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.device"),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="dst_ip",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="dst_port",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="flow_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="gid",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="protocol",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="rev",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="severity",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="signature_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="src_ip",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="src_port",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="timestamp",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="application_category_name",
            field=models.CharField(default="unknown", max_length=512),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="application_name",
            field=models.CharField(default="unknown", max_length=512),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="bidirectional_bytes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="bidirectional_duration_ms",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="bidirectional_packets",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="client_fingerprint",
            field=models.CharField(default="unknown", max_length=512),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="community_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="community_id_b64",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="device",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.device"),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="dst2src_bytes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="dst_ip",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="dst_mac",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="dst_port",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="ip_version",
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="protocol",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="protocol_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="requested_server_name",
            field=models.CharField(default="unknown", max_length=512),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="risk",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="server_fingerprint",
            field=models.CharField(default="unknown", max_length=512),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="src2dst_bytes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="src_ip",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="src_mac",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="src_port",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="timestamp",
            field=models.FloatField(),
        ),
    ]
