# Generated by Django 4.2.20 on 2026-02-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_alter_networkalert_options_alter_networkdpi_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkdpi",
            name="application_category_name",
            field=models.CharField(blank=True, default="unknown", max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="application_name",
            field=models.CharField(blank=True, default="unknown", max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="client_fingerprint",
            field=models.CharField(blank=True, default="unknown", max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="protocol",
            field=models.CharField(blank=True, default="unknown", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="requested_server_name",
            field=models.CharField(blank=True, default="unknown", max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="server_fingerprint",
            field=models.CharField(blank=True, default="unknown", max_length=512, null=True),
        ),
    ]
