# Generated by Django 4.2.20 on 2026-02-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_alter_networkdpi_application_category_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicemonitoring",
            options={"verbose_name": "Device monitoring", "verbose_name_plural": "Device monitoring"},
        ),
        migrations.AlterField(
            model_name="networkalert",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="networkdpi",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
