# Generated by Django 4.2.20 on 2026-02-26 11:52

import colander.core.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0075_alter_devicemonitoring_options_alter_networkalert_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicemonitoring",
            name="authentication_token",
        ),
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("token", models.CharField(default=colander.core.models._generate_token, max_length=128)),
                (
                    "views",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=128), default=list, size=None
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="devicemonitoring",
            name="api_token",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.apitoken"
            ),
        ),
    ]
