# Generated by Django 4.2.20 on 2026-02-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_remove_devicemonitoring_authentication_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemonitoring",
            name="started_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="PiRogueUserAccessSharing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_access_index", models.IntegerField()),
                (
                    "pirogue_credentials",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="core.piroguecredentials",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="core.colanderteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "PiRogue UserAccess sharing",
                "unique_together": {("pirogue_credentials", "user_access_index", "team")},
            },
        ),
    ]
