# Generated by Django 4.2.20 on 2026-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_alter_devicemonitoring_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="piroguecredentials",
            name="operating_mode",
            field=models.CharField(blank=True, help_text="Last known operating mode.", max_length=32, null=True),
        ),
    ]
