# Generated by Django 4.2.20 on 2026-02-27 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_piroguecredentials_operating_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemonitoring",
            name="ip_filter",
            field=models.CharField(
                blank=True,
                help_text="An IP address filter to be monitored (both IPv4 and IPv6 are supported).",
                max_length=64,
                null=True,
                validators=[django.core.validators.validate_ipv46_address],
            ),
        ),
    ]
