# Generated by Django 4.2.20 on 2026-03-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_devicemonitoring_ip_filter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networkalert",
            name="device",
        ),
        migrations.RemoveField(
            model_name="networkdpi",
            name="device",
        ),
        migrations.AddField(
            model_name="networkalert",
            name="device_monitoring",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="core.devicemonitoring"),
        ),
        migrations.AddField(
            model_name="networkdpi",
            name="device_monitoring",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="core.devicemonitoring"),
        ),
    ]
