# Generated by Django 4.2.20 on 2026-03-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_remove_networkalert_device_remove_networkdpi_device_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkalert",
            name="flow_id",
            field=models.BigIntegerField(default=0),
        ),
    ]
