# Generated by Django 4.2.20 on 2026-05-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_alter_networkalert_flow_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="analysis",
            field=models.JSONField(default=dict),
        ),
    ]
