# Generated by Django 4.2.20 on 2025-05-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_contributor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferences",
            field=models.JSONField(blank=True, null=True, verbose_name="User preferences"),
        ),
    ]
