# Generated by Django 3.2.15 on 2022-11-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonmodel',
            name='description',
            field=models.TextField(blank=True, help_text='Add more details about this object.', null=True),
        ),
    ]
