# Generated by Django 3.2.15 on 2022-12-11 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20221211_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='observable',
            name='es_prefix',
            field=models.CharField(default='4p8zzsvcxrxdih0f', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='case',
            name='es_prefix',
            field=models.CharField(default='n49cj81awoywy4hu', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='first_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 12, 41, 47, 614408, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 12, 41, 47, 614433, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
    ]
