# Generated by Django 3.2.15 on 2022-12-12 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20221211_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='piroguedump',
            name='name',
            field=models.CharField(default='NA', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='es_prefix',
            field=models.CharField(default='dvdq87jkjk2l2l7p', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='first_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 15, 55, 47, 377775, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 15, 55, 47, 377799, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='es_prefix',
            field=models.CharField(default='g1odxmmd5rkq0rq7', editable=False, max_length=16),
        ),
    ]
