# Generated by Django 3.2.15 on 2023-01-12 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20221212_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='es_prefix',
            field=models.CharField(default='7k08ox7wyrhwgu61', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='first_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 13, 9, 17, 248089, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 13, 9, 17, 248124, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='es_prefix',
            field=models.CharField(default='zfy3qbjs2ha3v8w3', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='piroguedump',
            name='analysis_index',
            field=models.CharField(default='7267i75g1swtsbx8', editable=False, help_text='Elasticsearch index storing the analysis.', max_length=16),
        ),
    ]
