# Generated by Django 3.2.15 on 2023-01-12 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230112_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='es_prefix',
            field=models.CharField(default='ugu7t8z1ms61d9l1', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='first_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 14, 43, 24, 459206, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 14, 43, 24, 459242, tzinfo=utc), help_text='First time the event has occurred.'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='es_prefix',
            field=models.CharField(default='mjo97ig79br4jxo3', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='piroguedump',
            name='analysis_index',
            field=models.CharField(default='jc60n48u2fj7xsrm', help_text='Elasticsearch index storing the analysis.', max_length=64),
        ),
    ]
